services:
  profile:
    image: profile-image
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 20M
    container_name: profile-container
    restart: unless-stopped
    build:
      context: .
    labels:
      - traefik.docker.network=traefik-public
      - traefik.enable=true
      - traefik.http.routers.profile.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.profile.middlewares=redirect@file
      - traefik.http.routers.profile.entrypoints=http
      - traefik.http.routers.profile_secure.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.profile_secure.tls=true
      - traefik.http.routers.profile_secure.entrypoints=https
    networks:
      - traefik-public

networks:
  traefik-public:
    external:
      name: traefik-public
